name: Check actions/cache
on: [push]
jobs:
  cache-artifact:
    runs-on: ubuntu-18.04
    steps:
      - name: Prepare ccache timestamp
        id: cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")
      - uses: pat-s/always-upload-cache@v2.1.0
        with:
          path: ../cache
          key: ${{ runner.os }}-v1-${{ steps.cache_timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ runner.os }}-v1-
      - name: Create cachable file
        run: |
          mkdir -p ../cache
          touch ../cache/foo.txt
